/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimetableRouteImport } from './routes/timetable'
import { Route as LecturersRouteImport } from './routes/lecturers'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ConflictsRouteImport } from './routes/conflicts'
import { Route as ClassroomsRouteImport } from './routes/classrooms'
import { Route as IndexRouteImport } from './routes/index'

const TimetableRoute = TimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturersRoute = LecturersRouteImport.update({
  id: '/lecturers',
  path: '/lecturers',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ConflictsRoute = ConflictsRouteImport.update({
  id: '/conflicts',
  path: '/conflicts',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassroomsRoute = ClassroomsRouteImport.update({
  id: '/classrooms',
  path: '/classrooms',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/classrooms': typeof ClassroomsRoute
  '/conflicts': typeof ConflictsRoute
  '/courses': typeof CoursesRoute
  '/lecturers': typeof LecturersRoute
  '/timetable': typeof TimetableRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/classrooms': typeof ClassroomsRoute
  '/conflicts': typeof ConflictsRoute
  '/courses': typeof CoursesRoute
  '/lecturers': typeof LecturersRoute
  '/timetable': typeof TimetableRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/classrooms': typeof ClassroomsRoute
  '/conflicts': typeof ConflictsRoute
  '/courses': typeof CoursesRoute
  '/lecturers': typeof LecturersRoute
  '/timetable': typeof TimetableRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/classrooms'
    | '/conflicts'
    | '/courses'
    | '/lecturers'
    | '/timetable'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/classrooms'
    | '/conflicts'
    | '/courses'
    | '/lecturers'
    | '/timetable'
  id:
    | '__root__'
    | '/'
    | '/classrooms'
    | '/conflicts'
    | '/courses'
    | '/lecturers'
    | '/timetable'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClassroomsRoute: typeof ClassroomsRoute
  ConflictsRoute: typeof ConflictsRoute
  CoursesRoute: typeof CoursesRoute
  LecturersRoute: typeof LecturersRoute
  TimetableRoute: typeof TimetableRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timetable': {
      id: '/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof TimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecturers': {
      id: '/lecturers'
      path: '/lecturers'
      fullPath: '/lecturers'
      preLoaderRoute: typeof LecturersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conflicts': {
      id: '/conflicts'
      path: '/conflicts'
      fullPath: '/conflicts'
      preLoaderRoute: typeof ConflictsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classrooms': {
      id: '/classrooms'
      path: '/classrooms'
      fullPath: '/classrooms'
      preLoaderRoute: typeof ClassroomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClassroomsRoute: ClassroomsRoute,
  ConflictsRoute: ConflictsRoute,
  CoursesRoute: CoursesRoute,
  LecturersRoute: LecturersRoute,
  TimetableRoute: TimetableRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
